---
- name: 打包工具
  shell: |
    WORK_DIR="$(cd ../;pwd)"
    OUTPUT_DIR="${WORK_DIR}"/roles/dispatch_tool/files/
    OUTPUT_FILE="${OUTPUT_DIR}"/tsc_sysinfo.tar.gz
    mkdir -p "${OUTPUT_DIR}"
    unlink "${OUTPUT_FILE}" &>/dev/null
    cd "${WORK_DIR}"
    tar czf "${OUTPUT_FILE}" --exclude-from="${WORK_DIR}"/etc/ignorelist \
      run.sh \
      globe.common.conf etc/globe.common.conf \
      bin/func bin/tsc_sysinfo_func.sh \
      modules
