---
- name: 汇总 基础环境完工检查 结果
  shell:
    cmd: |
      source /home/tsc/pyenv_profile
      python3 "${PWD}"/../bin/parse_result.py
  # register: parse_result
  # delegate_to: localhost
# - set_fact:
#     tsc_tools_version: "{{ tsc_tools_version_stdout.stdout }}"
- debug:
    msg: '结果查看: batch_logs/delivery.xlsx'
  # delegate_to: localhost
